
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int SELECT = 2;
  public static final int SMALLER = 14;
  public static final int PRODUCT = 9;
  public static final int EQUAL = 15;
  public static final int PROJECT = 3;
  public static final int ATTRIBUTE = 11;
  public static final int GEQUAL = 16;
  public static final int LEQUAL = 17;
  public static final int GREATER = 13;
  public static final int TABLE = 12;
  public static final int QUOTE = 22;
  public static final int RIGHT = 21;
  public static final int RJOIN = 6;
  public static final int LEFT = 20;
  public static final int COMMA = 19;
  public static final int NEQUAL = 18;
  public static final int EOF = 0;
  public static final int NUMBER = 10;
  public static final int UNION = 4;
  public static final int error = 1;
  public static final int LJOIN = 7;
  public static final int INTER = 5;
  public static final int JOIN = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SELECT",
  "PROJECT",
  "UNION",
  "INTER",
  "RJOIN",
  "LJOIN",
  "JOIN",
  "PRODUCT",
  "NUMBER",
  "ATTRIBUTE",
  "TABLE",
  "GREATER",
  "SMALLER",
  "EQUAL",
  "GEQUAL",
  "LEQUAL",
  "NEQUAL",
  "COMMA",
  "LEFT",
  "RIGHT",
  "QUOTE"
  };
}

